'use client';

// app/processor/new-batch-form.tsx
//
// Phase 4 — processor enters a completed processing batch.
//
// Inputs the staff member fills in:
//   - raw product (lookup from products table)
//   - raw_weight_lbs, raw_cost_total
//   - total_finished_weight_lbs, optional waste override
//   - processing + storage location (from inventory_locations)
//   - best_before_date, notes
//
// Computed and shown live so the staff can sanity-check before submitting:
//   - raw_cost_per_lb
//   - total_waste_weight_lbs (auto = raw - finished, can be overridden)
//   - yield_percent + yield_loss_percent
//   - effective_cost_per_finished_lb
//
// On submit: status='draft' so the founder approval queue picks it up.
// batch_number is auto-generated by a DB trigger (per founder context).

import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';

const NAVY = '#060e1c';
const PANEL = '#0f1a2e';
const GOLD = '#c8860f';
const GOLD_BRIGHT = '#f4c842';
const TEXT_DIM = 'rgba(255,255,255,0.55)';
const BORDER = 'rgba(255,255,255,0.08)';
const RED = '#f87171';
const GREEN = '#4ade80';

type Product = { id: string; name: string; sku?: string | null };
type Location = { id: string; code: string; name: string };

type Props = {
  userId: string;
  onCancel: () => void;
  onSubmitted: () => void;
};

export default function NewBatchForm({ userId, onCancel, onSubmitted }: Props) {
  // Reference data
  const [products, setProducts] = useState<Product[]>([]);
  const [locations, setLocations] = useState<Location[]>([]);
  const [refError, setRefError] = useState<string | null>(null);

  // Form state
  const [productId, setProductId] = useState('');
  const [productSearch, setProductSearch] = useState('');
  const [rawWeight, setRawWeight] = useState('');
  const [rawCostTotal, setRawCostTotal] = useState('');
  const [finishedWeight, setFinishedWeight] = useState('');
  const [wasteOverride, setWasteOverride] = useState('');
  const [processingLocationId, setProcessingLocationId] = useState('');
  const [storageLocationId, setStorageLocationId] = useState('');
  const [bestBefore, setBestBefore] = useState('');
  const [notes, setNotes] = useState('');

  // Submit state
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const [{ data: prods, error: prodErr }, locRes] = await Promise.all([
        supabase
          .from('products')
          .select('id, name, sku')
          .order('name')
          .limit(500),
        fetch('/api/locations', { cache: 'no-store' }).then((r) => r.json()),
      ]);
      if (cancelled) return;
      if (prodErr) {
        setRefError(`Could not load products: ${prodErr.message}`);
      } else {
        setProducts((prods || []) as Product[]);
      }
      if (Array.isArray(locRes?.locations)) {
        setLocations(locRes.locations as Location[]);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  // ─── Derived calculations ───────────────────────────────────────────
  const rawW = parseFloat(rawWeight) || 0;
  const rawCost = parseFloat(rawCostTotal) || 0;
  const finishedW = parseFloat(finishedWeight) || 0;
  const wasteOverrideN = wasteOverride === '' ? null : parseFloat(wasteOverride);

  const rawCostPerLb = rawW > 0 ? rawCost / rawW : 0;
  const computedWaste = Math.max(0, rawW - finishedW);
  const wasteW = wasteOverrideN ?? computedWaste;
  const yieldPct = rawW > 0 ? (finishedW / rawW) * 100 : 0;
  const yieldLossPct = rawW > 0 ? 100 - yieldPct : 0;
  const effectiveCostPerFinishedLb = finishedW > 0 ? rawCost / finishedW : 0;

  const calcReady = rawW > 0 && rawCost > 0 && finishedW > 0;
  const formValid = productId && calcReady && finishedW <= rawW;

  // ─── Filtered product list for the picker ───────────────────────────
  const productMatches = productSearch
    ? products
        .filter((p) => {
          const q = productSearch.toLowerCase();
          return (
            p.name.toLowerCase().includes(q) ||
            (p.sku ?? '').toLowerCase().includes(q)
          );
        })
        .slice(0, 8)
    : [];
  const selectedProduct = products.find((p) => p.id === productId);

  // ─── Submit ─────────────────────────────────────────────────────────
  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (!formValid) return;
    setSubmitting(true);
    setSubmitError(null);

    const nowIso = new Date().toISOString();
    const payload: Record<string, unknown> = {
      raw_product_id: productId,
      raw_weight_lbs: rawW,
      raw_cost_total: rawCost,
      raw_cost_per_lb: round4(rawCostPerLb),
      total_finished_weight_lbs: finishedW,
      total_waste_weight_lbs: round4(wasteW),
      yield_percent: round2(yieldPct),
      yield_loss_percent: round2(yieldLossPct),
      effective_cost_per_finished_lb: round4(effectiveCostPerFinishedLb),
      status: 'draft',
      created_by: userId,
      processed_by: userId,
      processed_at: nowIso,
      process_started_at: nowIso,
      process_completed_at: nowIso,
      notes: notes.trim() || null,
    };
    if (processingLocationId) payload.processing_location_id = processingLocationId;
    if (storageLocationId) payload.storage_location_id = storageLocationId;
    if (bestBefore) payload.best_before_date = bestBefore;

    const { error } = await supabase.from('processing_batches').insert(payload);
    setSubmitting(false);

    if (error) {
      setSubmitError(error.message);
      return;
    }
    onSubmitted();
  }

  return (
    <div
      style={{
        background: PANEL,
        border: `1px solid ${BORDER}`,
        borderRadius: 14,
        padding: 18,
      }}
    >
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'baseline',
          marginBottom: 14,
        }}
      >
        <h2
          style={{
            fontSize: 16,
            fontWeight: 800,
            margin: 0,
            color: '#fff',
          }}
        >
          New processing batch
        </h2>
        <button
          type="button"
          onClick={onCancel}
          style={{
            background: 'transparent',
            color: TEXT_DIM,
            border: `1px solid ${BORDER}`,
            borderRadius: 8,
            padding: '5px 10px',
            fontSize: 11,
            cursor: 'pointer',
          }}
        >
          ← Back
        </button>
      </div>

      {refError && (
        <FlashRow tone="warn" text={refError} />
      )}

      <form onSubmit={submit}>
        {/* Raw product picker */}
        <FieldLabel>Raw product</FieldLabel>
        {selectedProduct ? (
          <div
            style={{
              background: 'rgba(74,222,128,0.1)',
              border: `1px solid ${GREEN}33`,
              borderRadius: 10,
              padding: '10px 12px',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              marginBottom: 8,
            }}
          >
            <div>
              <div style={{ color: '#fff', fontSize: 14, fontWeight: 700 }}>
                {selectedProduct.name}
              </div>
              {selectedProduct.sku && (
                <div
                  style={{
                    color: TEXT_DIM,
                    fontSize: 11,
                    fontFamily: 'monospace',
                  }}
                >
                  {selectedProduct.sku}
                </div>
              )}
            </div>
            <button
              type="button"
              onClick={() => {
                setProductId('');
                setProductSearch('');
              }}
              style={{
                background: 'transparent',
                color: TEXT_DIM,
                border: `1px solid ${BORDER}`,
                borderRadius: 8,
                padding: '4px 10px',
                fontSize: 11,
                cursor: 'pointer',
              }}
            >
              Change
            </button>
          </div>
        ) : (
          <>
            <input
              type="text"
              value={productSearch}
              onChange={(e) => setProductSearch(e.target.value)}
              placeholder="Search products by name or SKU"
              style={inputStyle}
              autoComplete="off"
            />
            {productSearch && productMatches.length > 0 && (
              <div
                style={{
                  background: 'rgba(255,255,255,0.04)',
                  border: `1px solid ${BORDER}`,
                  borderRadius: 8,
                  marginTop: 6,
                  overflow: 'hidden',
                }}
              >
                {productMatches.map((p) => (
                  <button
                    key={p.id}
                    type="button"
                    onClick={() => {
                      setProductId(p.id);
                      setProductSearch('');
                    }}
                    style={{
                      width: '100%',
                      background: 'transparent',
                      border: 'none',
                      borderBottom: `1px solid ${BORDER}`,
                      color: '#fff',
                      padding: '10px 12px',
                      textAlign: 'left',
                      cursor: 'pointer',
                    }}
                  >
                    <div style={{ fontSize: 13, fontWeight: 600 }}>{p.name}</div>
                    {p.sku && (
                      <div
                        style={{
                          fontSize: 10,
                          color: TEXT_DIM,
                          fontFamily: 'monospace',
                        }}
                      >
                        {p.sku}
                      </div>
                    )}
                  </button>
                ))}
              </div>
            )}
            {productSearch && productMatches.length === 0 && (
              <div
                style={{
                  color: TEXT_DIM,
                  fontSize: 12,
                  marginTop: 6,
                }}
              >
                No matches. Add the product in /products first.
              </div>
            )}
          </>
        )}

        {/* Raw weight + cost */}
        <div style={{ display: 'flex', gap: 10 }}>
          <div style={{ flex: 1 }}>
            <FieldLabel>Raw weight (lbs)</FieldLabel>
            <input
              type="number"
              inputMode="decimal"
              step="0.01"
              min="0"
              value={rawWeight}
              onChange={(e) => setRawWeight(e.target.value)}
              placeholder="79.80"
              style={inputStyle}
            />
          </div>
          <div style={{ flex: 1 }}>
            <FieldLabel>Raw cost total (BSD)</FieldLabel>
            <input
              type="number"
              inputMode="decimal"
              step="0.01"
              min="0"
              value={rawCostTotal}
              onChange={(e) => setRawCostTotal(e.target.value)}
              placeholder="456.48"
              style={inputStyle}
            />
          </div>
        </div>

        {/* Finished weight + waste override */}
        <div style={{ display: 'flex', gap: 10 }}>
          <div style={{ flex: 1 }}>
            <FieldLabel>Finished weight (lbs)</FieldLabel>
            <input
              type="number"
              inputMode="decimal"
              step="0.01"
              min="0"
              value={finishedWeight}
              onChange={(e) => setFinishedWeight(e.target.value)}
              placeholder="44.50"
              style={inputStyle}
            />
          </div>
          <div style={{ flex: 1 }}>
            <FieldLabel>Waste override (lbs)</FieldLabel>
            <input
              type="number"
              inputMode="decimal"
              step="0.01"
              min="0"
              value={wasteOverride}
              onChange={(e) => setWasteOverride(e.target.value)}
              placeholder={
                rawW > 0 && finishedW > 0
                  ? `auto: ${computedWaste.toFixed(2)}`
                  : 'auto'
              }
              style={inputStyle}
            />
          </div>
        </div>

        {/* Locations */}
        {locations.length > 0 && (
          <div style={{ display: 'flex', gap: 10 }}>
            <div style={{ flex: 1 }}>
              <FieldLabel>Processing location</FieldLabel>
              <select
                value={processingLocationId}
                onChange={(e) => setProcessingLocationId(e.target.value)}
                style={{ ...inputStyle, appearance: 'none' }}
              >
                <option value="" style={{ background: PANEL }}>
                  — none —
                </option>
                {locations.map((l) => (
                  <option
                    key={l.id}
                    value={l.id}
                    style={{ background: PANEL }}
                  >
                    {l.code} · {l.name}
                  </option>
                ))}
              </select>
            </div>
            <div style={{ flex: 1 }}>
              <FieldLabel>Storage location</FieldLabel>
              <select
                value={storageLocationId}
                onChange={(e) => setStorageLocationId(e.target.value)}
                style={{ ...inputStyle, appearance: 'none' }}
              >
                <option value="" style={{ background: PANEL }}>
                  — none —
                </option>
                {locations.map((l) => (
                  <option
                    key={l.id}
                    value={l.id}
                    style={{ background: PANEL }}
                  >
                    {l.code} · {l.name}
                  </option>
                ))}
              </select>
            </div>
          </div>
        )}

        {/* Best-before + notes */}
        <FieldLabel>Best before (optional)</FieldLabel>
        <input
          type="date"
          value={bestBefore}
          onChange={(e) => setBestBefore(e.target.value)}
          style={inputStyle}
        />

        <FieldLabel>Notes (optional)</FieldLabel>
        <textarea
          rows={2}
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
          placeholder="Anything the founder should know during review"
          style={{ ...inputStyle, resize: 'vertical', minHeight: 56 }}
        />

        {/* Live calculations */}
        <div
          style={{
            background: 'rgba(244,200,66,0.06)',
            border: `1px solid ${GOLD}33`,
            borderRadius: 10,
            padding: 14,
            marginTop: 18,
          }}
        >
          <div
            style={{
              fontSize: 10,
              letterSpacing: 1,
              color: GOLD,
              fontWeight: 700,
              textTransform: 'uppercase',
              marginBottom: 10,
            }}
          >
            Live calculations
          </div>
          <CalcRow label="Raw cost per lb"            value={fmt$(rawCostPerLb)} />
          <CalcRow label="Total waste"                value={`${wasteW.toFixed(2)} lb`} />
          <CalcRow label="Yield"                      value={`${yieldPct.toFixed(1)}%`} good />
          <CalcRow label="Yield loss"                 value={`${yieldLossPct.toFixed(1)}%`} />
          <CalcRow
            label="Effective cost per finished lb"
            value={fmt$(effectiveCostPerFinishedLb)}
            good
          />
        </div>

        {finishedW > rawW && rawW > 0 && (
          <FlashRow
            tone="warn"
            text="Finished weight cannot exceed raw weight."
          />
        )}

        {submitError && (
          <FlashRow tone="warn" text={`Could not save: ${submitError}`} />
        )}

        <div style={{ display: 'flex', gap: 10, marginTop: 18 }}>
          <button
            type="button"
            onClick={onCancel}
            disabled={submitting}
            style={{
              flex: 1,
              padding: '13px 0',
              borderRadius: 10,
              border: `1px solid ${BORDER}`,
              background: 'transparent',
              color: TEXT_DIM,
              fontWeight: 700,
              fontSize: 13,
              cursor: submitting ? 'not-allowed' : 'pointer',
            }}
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={!formValid || submitting}
            style={{
              flex: 2,
              padding: '13px 0',
              borderRadius: 10,
              border: 'none',
              background: !formValid || submitting ? '#4b5563' : GOLD_BRIGHT,
              color: NAVY,
              fontWeight: 900,
              fontSize: 14,
              cursor: !formValid || submitting ? 'not-allowed' : 'pointer',
            }}
          >
            {submitting ? 'Saving…' : 'Submit for founder review'}
          </button>
        </div>
      </form>
    </div>
  );
}

/* ───────── helpers ───────── */

function fmt$(n: number): string {
  return `$${n.toFixed(2)}`;
}
function round2(n: number) {
  return Math.round(n * 100) / 100;
}
function round4(n: number) {
  return Math.round(n * 10000) / 10000;
}

function FieldLabel({ children }: { children: React.ReactNode }) {
  return (
    <label
      style={{
        display: 'block',
        fontSize: 11,
        letterSpacing: 1,
        color: TEXT_DIM,
        fontWeight: 700,
        textTransform: 'uppercase',
        margin: '14px 0 6px',
      }}
    >
      {children}
    </label>
  );
}

function CalcRow({
  label,
  value,
  good,
}: {
  label: string;
  value: string;
  good?: boolean;
}) {
  return (
    <div
      style={{
        display: 'flex',
        justifyContent: 'space-between',
        padding: '4px 0',
        fontSize: 12,
      }}
    >
      <span style={{ color: TEXT_DIM }}>{label}</span>
      <span
        style={{
          color: good ? GREEN : '#fff',
          fontWeight: 700,
        }}
      >
        {value}
      </span>
    </div>
  );
}

function FlashRow({
  tone,
  text,
}: {
  tone: 'warn' | 'info';
  text: string;
}) {
  const color = tone === 'warn' ? RED : GOLD_BRIGHT;
  const bg =
    tone === 'warn' ? 'rgba(248,113,113,0.08)' : 'rgba(244,200,66,0.08)';
  return (
    <div
      style={{
        background: bg,
        border: `1px solid ${color}33`,
        color,
        borderRadius: 10,
        padding: '10px 12px',
        fontSize: 12,
        fontWeight: 600,
        marginTop: 12,
      }}
    >
      ⚠️ {text}
    </div>
  );
}

const inputStyle: React.CSSProperties = {
  width: '100%',
  padding: '12px 14px',
  borderRadius: 10,
  border: `1.5px solid ${BORDER}`,
  background: 'rgba(255,255,255,0.04)',
  color: '#fff',
  fontSize: 14,
  outline: 'none',
  boxSizing: 'border-box',
};
