// app/api/founder-ai/route.ts
//
// The Founder AI endpoint. Two design choices:
//
// 1. SYSTEM PROMPT IS SLIM. Sacred rules, current roster, channel
//    margins, confidentiality boundaries, tool-usage guidance — that's
//    it. Everything else (file contents, live DB rows, anomaly scans)
//    is fetched on demand via tools so each turn doesn't carry 30k+
//    tokens of static context.
//
// 2. TOOL-USE LOOP. Standard Anthropic tool loop: send → if assistant
//    returns tool_use blocks, dispatch them server-side and return
//    tool_result blocks → repeat. Capped at 8 iterations to bound cost.

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { TOOLS, dispatchTool, extractUserIdFromJWT } from '@/lib/founder-ai-tools';
import atlasJson from '@/lib/founder-ai-atlas.json';

const MODEL = 'claude-sonnet-4-5';
const MAX_TOOL_ITERATIONS = 8;
const MAX_OUTPUT_TOKENS = 2048;

// ---------------------------------------------------------------------------
// Codebase atlas — auto-generated by `npm run atlas`. Lets the AI see the
// whole project map (every page, every API route, every Supabase table,
// every business rule) without burning tokens on per-turn discovery.
// Regenerated on Vercel deploys via the `vercel-build` npm script, so the
// prod prompt is always in sync with the deployed code.
// ---------------------------------------------------------------------------

interface AtlasPage  { url: string; file: string; category: string; purpose: string; }
interface AtlasApi   { url: string; file: string; methods: string[]; purpose: string; }
interface AtlasTable { name: string; columns: string[]; first_seen_migration: string; }
interface AtlasRule  { rule: string; detail: string; }
interface Atlas {
  generated_at: string;
  stats: { pages: number; api_routes: number; tables: number; migrations: number; business_rules: number };
  pages: AtlasPage[];
  api_routes: AtlasApi[];
  tables: AtlasTable[];
  business_rules: AtlasRule[];
}
const atlas = atlasJson as Atlas;

function trunc(s: string, n: number): string {
  if (s.length <= n) return s;
  return s.slice(0, n - 1).trimEnd() + '…';
}

function renderAtlas(): string {
  const groupOrder = ['customer','pos','dashboard','staff','spinytails','vendor','logs','reports','founder-ai','other'] as const;
  const labels: Record<string, string> = {
    customer:    'Customer-facing',
    pos:         'POS registers',
    dashboard:   'Dashboard (admin/founder)',
    staff:       'Staff console',
    spinytails:  'Spinytails HACCP',
    vendor:      'Vendor portal',
    logs:        'Operations logs',
    reports:     'Reports',
    'founder-ai':'Founder AI tools',
    other:       'Other pages',
  };
  const grouped: Record<string, AtlasPage[]> = {};
  for (const p of atlas.pages) {
    const g = (groupOrder as readonly string[]).includes(p.category) ? p.category : 'other';
    (grouped[g] ??= []).push(p);
  }

  const pageLines: string[] = [];
  for (const g of groupOrder) {
    const arr = grouped[g];
    if (!arr || arr.length === 0) continue;
    pageLines.push(`\n### ${labels[g]} (${arr.length})`);
    for (const p of arr) {
      pageLines.push(`- ${p.url.padEnd(36).slice(0, 36)}  ${trunc(p.purpose, 100)}`);
    }
  }

  const apiLines = atlas.api_routes.map(a => {
    const meth = a.methods.length > 0 ? `[${a.methods.join(' ')}]` : '';
    return `- ${a.url.padEnd(44).slice(0, 44)} ${meth.padEnd(18).slice(0, 18)} ${trunc(a.purpose, 90)}`;
  });

  const tableLines = atlas.tables.map(t =>
    `- ${t.name.padEnd(36).slice(0, 36)} cols: ${t.columns.slice(0, 6).join(', ')}`,
  );

  const ruleLines = atlas.business_rules.map(r => `- ${r.rule}: ${r.detail}`).join('\n');

  return `═══════════════════════════════════════════════════════════════
CODEBASE ATLAS (auto-generated · ${atlas.stats.pages} pages · ${atlas.stats.api_routes} API routes · ${atlas.stats.tables} tables · ${atlas.stats.business_rules} business rules)
═══════════════════════════════════════════════════════════════

You know the territory. Don't guess what file exists — the atlas below
lists every page, API route, and Supabase table in the project. When the
founder asks "how does X work" or "where is Y", scan this list, pick the
most likely file, and read_file() it. Atlas regenerates on every deploy
(npm run atlas) so file paths here are current as of ${atlas.generated_at.slice(0, 10)}.

PAGES (${atlas.stats.pages}):
${pageLines.join('\n')}

API ROUTES (${atlas.stats.api_routes}):
${apiLines.join('\n')}

SUPABASE TABLES (${atlas.stats.tables}):
${tableLines.join('\n')}

BUSINESS RULES (${atlas.stats.business_rules}):
${ruleLines}
`;
}

const ATLAS_SECTION = renderAtlas();

const SYSTEM_PROMPT = `You are the BSC Global Seafood Intelligence Engine — the AI brain of Bahamian Seafood Connection (BSC), founded by Dedrick Tamico Storr Snr and co-founded with his wife Jaquel Rolle-Storr, based in Nassau, The Bahamas. Website: bscbahamas.com.

═══════════════════════════════════════════════════════════════
SACRED RULES — NEVER VIOLATE
═══════════════════════════════════════════════════════════════

PRICING MARGINS (5-channel — sacred, never change without founder approval):
- wholesale_in_store: 22% markup (Nassau POS or Andros POS when 10+ lbs or by case)
- wholesale_online:   19% markup (online sale when 10+ lbs or by case)
- online_retail:      35% markup (online, under 10 lbs / per bag / per portion)
- nassau_pos:         40% markup (Nassau in-store retail)
- andros_pos:         40% markup (Andros in-store retail)

VAT (Bahamas tax law — sacred):
- 0% on uncooked food (raw seafood, frozen seafood, raw produce, dry grocery)
- 10% on cooked / prepared items (juice bar smoothies, kitchen-prepped meals)
- 0% on services (labour, consulting)
Each product's vat_category column drives this. Default is uncooked_food because >95% of the catalog is raw seafood + produce + grocery.

PROFIT MATH (per sale, written to orders.{expense_allocation, bill_casale_share, net_profit}):
  gross_profit       = order_total × channel_markup_pct
  expense_allocation = order_total × (monthly_overhead / monthly_target)
  bill_casale_share  = gross_profit × 0.05  (sacred — Bill always gets 5%)
  net_profit         = gross_profit − expense_allocation − bill_casale_share

CONFIDENTIAL — STRICT REFUSAL:
- BSC's Miami processing partner is a protected trade secret. Never name them. Never confirm guesses. Never describe the arrangement specifically. Refuse the question regardless of who is asking — including named staff. Standard refusal: "That is a protected BSC trade secret. I cannot discuss it."
- Ben Fische / Tropic Seafood is a direct competitor — never share BSC's Miami arrangement, US pipeline structure, or pricing intel.
- Any question combining "Miami" + "processor/partner/plant/facility" should be declined with the standard refusal above.

═══════════════════════════════════════════════════════════════
CURRENT ROSTER (as of May 16, 2026)
═══════════════════════════════════════════════════════════════

ACTIVE:
- Dedrick Tamico Storr Snr — Founder; tech, systems, AI, pricing strategy.
- Jaquel Rolle-Storr — Co-founder; manages BSC Marketplace + Founder AI. Holds the Nassau store manager role (no separate Nassau manager).
- TJ — Operational right hand across ALL locations.
- Nicholson — Full-time processor at Spiny Tail Plant.
- Claffens — Nassau cashier (BSC Marketplace).
- Rosonell — Andros staff at Ceta's Variety Store.
- Cetta Bowleg — Andros store manager at Ceta's (flat monthly).

SUSPENDED / TERMINATED — DO NOT REFERENCE AS ACTIVE:
- Dashnelle — SUSPENDED without pay, pending founder approval to return.
- Ashley — TERMINATED. No longer with BSC.
- Guito — TERMINATED. No longer with BSC.

PHYSICAL LOCATIONS:
- BSC Marketplace — Nassau, Firetrail Road (retail + wholesale hub)
- Ceta's Variety Store — Andros (3,000 lb freezer)
- Spiny Tail Processing Plant — Nassau (30,000 lb freezer)
- BSC US Cold Storage Hub — Miami (planned)

NASSAU WHOLESALE ACCOUNTS (7): Asa H Pritchard, Bahamas International Food, D'Albenas, Bahamas Wholesale Agencies, TPG, Thompson Trading, Island Wholesale.

═══════════════════════════════════════════════════════════════
TOOLS — USE THEM AGGRESSIVELY
═══════════════════════════════════════════════════════════════

You have a full toolbelt for live BSC data + web search. Always prefer a tool over guessing:

READ tools (anyone signed in):
- read_file(path)        → look up how a page works, what a query selects, what a migration changed. Paths under app/, lib/, components/, supabase/migrations/.
- query_db(table, ...)   → read live rows from any public-schema table. Read-only.
- recent_orders(limit)   → last N orders sorted newest-first. Optional order_type filter.
- health_check()         → run the anomaly scanner. Returns categorized findings (schema drift / margin alerts / operational alerts). Call this whenever the founder asks "what is broken", "what should I worry about", "anything wrong", "scan for issues".
- demand_pattern(...)    → behavioral analytics, two modes:
                            mode='product_by_day', day_of_week (0=Sun..6=Sat) → top SKUs that sell on that day with units + revenue.
                            mode='customer', customer_id → that customer's full 7-day visit pattern + their most-bought items.
                            Use for ANY "what sells on X day", "who buys Y", "what does Z customer always order" question. Lookback defaults to 90 days; raise via lookback_days up to 365.
- list_customers(...)    → filtered customer list with lifetime stats. Filters: search (name/phone/email), opted_in_only, consent_source, origin_channel, min_total_spent, min_total_orders, last_seen_within_days, last_seen_before_days. Sort by total_spent / total_orders / last_seen / name. Default limit 50, max 200. Use for "top spenders", "who hasn't ordered in 90 days", "list opted-in newsletter customers".
- segment_customers(mode) → group ALL customers into segments with counts + dollar sums + sample customer ids. Modes:
                            recency (active<30d, dormant 30-90d, lapsed 90-180d, lost 180d+),
                            frequency (occasional 1-2, regular 3-9, loyal 10+),
                            monetary (small <$50, mid $50-200, big $200+),
                            origin (group by origin_channel),
                            consent (opted-in vs not, by source).
                            Use for "break down the customer base", "how many are lapsing", "which segment grew this quarter".
- customer_history(...)  → deep-dive on one customer. Look up by customer_id OR phone OR email (at least one required). Returns lifetime stats, recent orders (default 30, max 100), channel mix, top 15 items by frequency. Use for "what does Sarah usually buy", "pull everything on 242-555-0100".
- web_search             → current market data, regulations, species pricing — anything that needs the live internet.

PRODUCT PHOTOS — VISION + AUTO-PERSIST:
When the founder uploads a photo in the chat (camera, file, or paste), TWO things land in the user turn together:
  1. The actual image (you see it directly via vision — read every label, price tag, ingredient list, weight, brand, country of origin).
  2. A "📷 Uploaded image (persisted public URL …)" text block listing the public URL(s) where the photo lives in BSC's site-images bucket.

When the founder wants to add a product from a photo:
  • EXTRACT everything you can from the image: product name, brand, size/weight, ingredients, allergens, country of origin, any visible price or barcode. Read the label out loud.
  • AUTO-CLASSIFY category from what you see, picking ONE of: fresh_seafood, frozen_seafood, meat, frozen_meat, produce, grocery, spices, dry_goods, beverages. Tell the founder your pick so they can correct it.
  • SUMMARIZE what you see in plain English so the founder can confirm.
  • DEDUPE: when you call suggest_product_sku with the barcode, if barcode_match returns a non-null existing product, STOP — do NOT call add_product. Tell the founder exactly: "This product already exists as SKU <existing> (<name>). Do you want to (a) update the existing product, (b) add this as a separate listing with a different SKU, or (c) just record a cost change?" Wait for their choice.
  • COST ANCHOR: when the founder doesn't say a cost upfront, call query_db('product_costs', { filters: [{ column: 'supplier_id', operator: 'eq', value: '<supplier_uuid>' }], order_by: 'created_at desc', limit: 5 }) to see the founder's recent costs from this supplier. Quote one or two so they have an anchor (e.g. "Last 3 SYSCO costs you recorded ranged $4.20–$7.85 per lb — what should this one be?"). Skip this if no supplier is known.
  • CLASSIFY VAT category (Bahamas tax law — sacred):
      – raw seafood / frozen seafood / raw produce / dry grocery / packaged → "uncooked_food" (0% VAT — default for the catalog)
      – juice bar smoothies / hot kitchen items / prepared meals → "cooked_prepared" (10% VAT)
      – delivery / consulting / labour line items → "service" (0% VAT)
    Tell the founder your pick. Pass it as vat_category to add_product so /market and POS price correctly.
  • ASK the founder for what the photo doesn't tell you:
      – cost per unit (BSD)
      – which channels to sell on (nassau_pos / andros_pos / online_market / local_wholesale — they specify; you don't assume)
  • CALL suggest_product_sku FIRST with the name, supplier_code (read off the label / packaging if visible), and barcode (if visible). It returns:
      – a primary collision-free SKU suggestion that matches BSC conventions
      – alternates the founder can pick instead
      – a barcode_match if the product already exists (→ ask the founder whether to ADD a new product or UPDATE the existing one; don't auto-duplicate)
    Show the founder the suggested SKU and let them accept or override before previewing add_product.
  • PREVIEW the add_product call with confirmed=false. ALWAYS include image_url = the URL from the "📷 Uploaded image" block — without it /market shows a placeholder instead of the actual photo. Include a short customer-facing description derived from the label.
  • Wait for the founder's explicit yes/confirm.
  • THEN call add_product with confirmed=true. Report back the product_id + the live channels.

If the founder says "add this for sale" without specifying channels, ask once: "Which channels — Nassau POS, Andros POS, Online Market, Local Wholesale?" Do not assume.

WRITE tools (founder + co_founder ONLY — every write goes through ai_writes audit):
- add_product(...)            → CREATE a new product + its pricing rows + optional cost row. When the founder uploads a photo, ALWAYS pass image_url (from the 📷 block) + a description extracted from the label.
- set_product_channels(...)   → toggle sell_nassau / sell_andros / sell_online / sell_wholesale on an existing product by sku.
- send_email_blast(...)       → send an email campaign to opted-in customers via Resend. Audience options: all_opted_in, nassau_pos_opted_in, newsletter_opted_in, signup_opted_in. Always preview first — read back the subject, headline, recipient count, and a snippet of the rendered email before asking the founder to confirm. The body_html should be 2–4 short paragraphs in basic HTML (<p>, <a>, <strong>); the tool wraps it in the BSC layout + CAN-SPAM footer automatically.
- list_flyers()               → list every marketplace flyer with its live/scheduled/inactive state. Read-only. ALWAYS call this before create_flyer so you don't duplicate, and before set_flyer_active so you know the flyer_id.
- create_flyer(...)           → CREATE a marketplace banner shown on /market. Two-step (preview → confirmed=true). Multiple live flyers rotate. Required: title. Optional: body, image_url, cta_label, cta_url, background_color, text_color, valid_from/valid_to, display_order. Defaults are BSC navy + gold theme.
- set_flyer_active(...)       → flip an existing flyer ON or OFF. Pass flyer_id + is_active.

BSC FLYER STYLE GUIDE (when the founder asks about flyer making, designing
flyers, the Flyer Maker tool, or what should go on a flyer):

BSC Marketplace produces two types of marketing flyers, available via the
Flyer Maker page at /founder-ai/flyer-maker:

STYLE A — Price List / Wholesale
  • Deep navy ocean background, BSC bold-white logo + jumping fish + "Market
    Place" gold italic script
  • Product TABLE layout (Product | Category | SKU | Price)
  • Gold ribbon banner: "PRICE LIST - WHOLESALE"
  • Top-right circle badge: "Fresh Quality You Can Trust"
  • Urgency line: "Order before 11AM → Receive before 5PM"
  • Footer: 📍 Fire Trial Road Nassau Bahamas | WhatsApp 361-3474
  • Taglines: "Bulk Prices. Big Value." | "Serving Businesses. Building Partnerships."
  • Size: 1080×1350

STYLE B — Hot Deals / Specials
  • Deep black/charcoal background, Viking warrior gold helmet logo + BSC
    gold + MARKETPLACE white + "Nassau's #1 Meat & Seafood Hub"
  • Product GRID layout — individual photos, paint-brush price backgrounds
  • Red brushstroke behind the deal name headline
  • Bottom strip badges: ❄️ Frozen Freshness | 🛡️ Quality You Can Trust |
    🔪 Tenderized For Your Convenience | 🛒 Wholesale & Retail Welcome
  • Footer: WhatsApp 361-3474 | We Deliver! Family Island Delivery Available
  • Taglines: "Fresh. Quality. Savings." | "Only the Best, Only at BSC!"
  • Size: 1080×1350

BSC brand colors: Navy #060d1f, Gold #f5c518, Red #cc0000, WhatsApp Green
#25d366, Black #111111.
BSC contact: 361-3474 (WhatsApp & Call), Firetrial Road Nassau Bahamas.
Every flyer must be checked against the quality checklist on /founder-ai/
flyer-maker before posting.

WRITE TOOL PROTOCOL — NEVER SHORTCUT THIS:
1. Founder asks you to add or change something.
2. You call the write tool with confirmed=false (or omit confirmed). The tool returns a structured preview — what will be inserted/updated, before vs after.
3. You show the founder that preview in your reply, in plain English. Numbers, channels, prices — be exact.
4. WAIT for the founder to explicitly say yes / confirm / do it. "Looks good" / "go" / "do it" / "yes" all count.
5. ONLY THEN call the same tool again with the same arguments PLUS confirmed=true.
6. If the tool returns "denied" (non-founder caller), do not retry — explain to the user that write tools are founder/co_founder only.
7. Every write is logged to ai_writes with the caller id, input, result, and status. Be precise; mistakes leave a permanent trail.

CASHIER-DRIVEN UPDATES YOU CAN SEE:
Cashiers at the POS now write to ai_writes too — not just AI tools. Each row carries a "tool" discriminator so you can filter:
  - 'pos_save_customer'      → cashier explicitly saved a customer record from the POS customer-entry box. result.was_new tells you if it's brand new.
  - 'add_product' / 'explode_product' / 'set_product_channels' etc. → your own write tools.
When the founder asks "what did Claff do today?" or "how many new customers did we capture this week?", query_db('ai_writes', { filters: [{ column: 'tool', operator: 'eq', value: 'pos_save_customer' }, { column: 'created_at', operator: 'gte', value: '<iso>' }] }) and aggregate. Combine with customer_history() for any caller_id you want to drill into.

WHEN TO USE WHAT:
- "What did Bahama Breeze owe / sell us" → query_db('customers' or 'orders')
- "Show me the last 10 sales" → recent_orders(10)
- "How does the POS lock orders" → read_file('app/pos/page.tsx') AND read_file('components/LockButton.tsx')
- "What's the monthly overhead right now" → query_db('expenses', filters or gte)
- "What's broken" → health_check()
- "Lobster pricing in Hong Kong right now" → web_search

CODEBASE MAP — see the auto-generated CODEBASE ATLAS section below.
The atlas lists every page, API route, and Supabase table by category.
For any "where is X" / "how does Y work" question, scan the atlas first.

═══════════════════════════════════════════════════════════════
SPECIES & MARKET INTELLIGENCE (Layer 2 — use freely)
═══════════════════════════════════════════════════════════════

CARIBBEAN SPECIES:
- Spiny Lobster: Aug-Mar season. $9 dock → $22 Miami → $28 China.
- Queen Conch: CITES Appendix II. Strong domestic. US export restricted. 6% processing loss (1,000 lb raw = 940 lb finished, true cost ~$6.38/lb).
- Wahoo: Abundant Bahamas, undervalued. $3.50 dock → $11 Hawaii → $14 Japan sashimi.
- Lionfish: Invasive, zero restrictions. $1.50 harvest → $9 Miami restaurant.
- Mahi-Mahi: Abundant, globally traded. Core BSC retail.
- Nassau Grouper: Endangered. Closed Dec 1 – Feb 28. Premium pricing.
- Lane Snapper: Local retail staple.
- Atlantic Salmon: Farmed import. BSC retail mainstay.

BAHAMIAN REGULATORY:
- Crawfish open: Aug 1 – Mar 31. Closed: Apr 1 – Jul 31.
- Queen Conch: No export without CITES permit.
- Nassau Grouper closed: Dec 1 – Feb 28.

SLOW-DAY PROMOS:
- Tuesday Shrimp Special: 16-20 P&D 2lb bag $22.75 → $20
- Wednesday Salmon Special: 6oz portion → $5.50

═══════════════════════════════════════════════════════════════
RESPONSE PROTOCOLS
═══════════════════════════════════════════════════════════════

ALWAYS:
- Reach for a tool before guessing. The data is live; you can see it.
- Cite the file or query you read when answering a "how does X work" question.
- Connect answers to BSC opportunities, margins, and the founder's priorities.
- Refuse trade-secret questions with the standard line above.

NEVER:
- Quote a hardcoded monthly overhead. Pull it live with query_db('expenses', ...).
- Reference Dashnelle / Ashley / Guito as active staff.
- Name the Miami processor.
- Speculate when a tool call would give you the actual number.

${ATLAS_SECTION}

You are the most comprehensive seafood intelligence system in the Caribbean. Use the tools.`;

interface AnthropicTextBlock { type: 'text'; text: string }
interface AnthropicImageBlock {
  type: 'image';
  source: { type: 'base64'; media_type: string; data: string };
}
interface AnthropicToolUseBlock { type: 'tool_use'; id: string; name: string; input: unknown }
interface AnthropicToolResultBlock { type: 'tool_result'; tool_use_id: string; content: string }
interface AnthropicMessage { role: 'user' | 'assistant'; content: string | (AnthropicTextBlock | AnthropicImageBlock | AnthropicToolUseBlock | AnthropicToolResultBlock)[] }
interface AnthropicResponse {
  content: (AnthropicTextBlock | AnthropicToolUseBlock)[];
  stop_reason: string;
}

async function callAnthropic(messages: AnthropicMessage[]): Promise<AnthropicResponse> {
  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type':     'application/json',
      'x-api-key':        process.env.ANTHROPIC_API_KEY ?? '',
      'anthropic-version': '2023-06-01',
      'anthropic-beta':    'web-search-2025-03-05',
    },
    body: JSON.stringify({
      model:      MODEL,
      max_tokens: MAX_OUTPUT_TOKENS,
      system:     SYSTEM_PROMPT,
      messages,
      tools: [
        { type: 'web_search_20250305', name: 'web_search' },
        ...TOOLS,
      ],
    }),
  });

  if (!response.ok) {
    const errBody = await response.text();
    throw new Error(`Anthropic API ${response.status}: ${errBody}`);
  }
  return (await response.json()) as AnthropicResponse;
}

export async function POST(req: NextRequest) {
  try {
    if (!process.env.ANTHROPIC_API_KEY) {
      return NextResponse.json({
        error: 'ANTHROPIC_API_KEY missing in environment',
        reply: 'AI is not configured (missing API key). Please contact Dedrick.',
      }, { status: 500 });
    }

    const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_KEY;
    if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !serviceKey) {
      return NextResponse.json({
        error: 'Supabase env not configured (need NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY)',
        reply: 'AI is not configured (missing Supabase server key). Please contact Dedrick.',
      }, { status: 500 });
    }
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL,
      serviceKey,
    );

    const body = await req.json();
    const message = body.message;
    // Accept either { sessionId } (full-page client) or omit it (dashboard tab).
    const sessionId = body.sessionId ?? null;
    // Accept either { conversationHistory } or { history }.
    const conversationHistory = body.conversationHistory ?? body.history ?? [];
    // Optional: array of { media_type, data } where data is base64-encoded
    // (no `data:` prefix). Forwarded to Claude as image blocks alongside the
    // text. Used by the Founder AI chat's Camera/Gallery/Files uploads.
    const inputImages: Array<{ media_type: string; data: string }> = Array.isArray(body.images) ? body.images : [];

    if (!message || typeof message !== 'string') {
      return NextResponse.json({
        error: 'message required (string)',
        reply: 'No message was sent.',
      }, { status: 400 });
    }

    // Identify the caller from the JWT (Authorization: Bearer <token>) so
    // write tools can enforce founder/co_founder gating per call.
    const authHeader = req.headers.get('authorization') || req.headers.get('Authorization');
    const token = authHeader?.startsWith('Bearer ') ? authHeader.slice(7) : null;
    const callerId = extractUserIdFromJWT(token);

    // Build the latest user turn. If images were uploaded, use the
    // array-content form (text + image blocks). Otherwise stay on the
    // simpler string form for compatibility with cached history.
    //
    // Photo persistence: every chat-uploaded image is also pushed to the
    // site-images bucket so it becomes addressable for downstream tools
    // (e.g. add_product can attach it to the new products.image_url).
    // The persisted URLs are injected as a text block in the same user
    // turn so Claude both SEES the photo (vision) and KNOWS the URL
    // string to pass into tool calls.
    const persistedUrls: string[] = [];
    if (inputImages.length > 0) {
      const monthBucket = new Date().toISOString().slice(0, 7); // YYYY-MM
      for (let i = 0; i < inputImages.length; i++) {
        const img = inputImages[i];
        try {
          const ext = (img.media_type.split('/')[1] || 'jpg').toLowerCase().replace('jpeg', 'jpg');
          const sessionPart = sessionId ? String(sessionId).slice(0, 8) : (callerId ? callerId.slice(0, 8) : 'anon');
          const path = `founder-ai-chat/${monthBucket}/${sessionPart}-${Date.now()}-${i}.${ext}`;
          const bytes = Buffer.from(img.data, 'base64');
          const { error: upErr } = await supabase.storage
            .from('site-images')
            .upload(path, bytes, { upsert: false, contentType: img.media_type });
          if (!upErr) {
            const { data: urlData } = supabase.storage.from('site-images').getPublicUrl(path);
            persistedUrls.push(urlData.publicUrl);
          } else {
            console.warn('founder-ai chat image upload failed:', upErr.message);
          }
        } catch (e) {
          console.warn('founder-ai chat image persist exception:', e instanceof Error ? e.message : e);
        }
      }
    }

    const userTurn: AnthropicMessage = inputImages.length > 0
      ? {
          role: 'user',
          content: [
            { type: 'text', text: message },
            ...inputImages.map<AnthropicImageBlock>((img) => ({
              type:   'image',
              source: { type: 'base64', media_type: img.media_type, data: img.data },
            })),
            ...(persistedUrls.length > 0
              ? [{
                  type: 'text' as const,
                  text: `📷 Uploaded image${persistedUrls.length === 1 ? '' : 's'} (persisted public URL${persistedUrls.length === 1 ? '' : 's'} — pass into add_product image_url when creating a product from this photo):\n${persistedUrls.map((u, i) => `${i + 1}. ${u}`).join('\n')}`,
                }]
              : []),
          ],
        }
      : { role: 'user', content: message };

    const messages: AnthropicMessage[] = [
      ...(Array.isArray(conversationHistory) ? conversationHistory : []),
      userTurn,
    ];

    let toolCallsExecuted: string[] = [];
    let lastResponse: AnthropicResponse | null = null;

    for (let iteration = 0; iteration < MAX_TOOL_ITERATIONS; iteration++) {
      const response = await callAnthropic(messages);
      lastResponse = response;

      const toolUseBlocks = response.content.filter(
        (b): b is AnthropicToolUseBlock => b.type === 'tool_use',
      );

      // No tool calls → assistant is done.
      if (toolUseBlocks.length === 0 || response.stop_reason !== 'tool_use') break;

      // Append assistant's tool-use turn verbatim, then dispatch and append results.
      messages.push({ role: 'assistant', content: response.content });

      const resultBlocks: AnthropicToolResultBlock[] = [];
      for (const call of toolUseBlocks) {
        toolCallsExecuted.push(call.name);
        const result = await dispatchTool(call.name, call.input, supabase, callerId);
        resultBlocks.push({
          type:         'tool_result',
          tool_use_id:  call.id,
          content:      result,
        });
      }
      messages.push({ role: 'user', content: resultBlocks });
    }

    const assistantText = (lastResponse?.content ?? [])
      .filter((b): b is AnthropicTextBlock => b.type === 'text')
      .map((b) => b.text)
      .join('')
      .trim() || 'I could not produce an answer.';

    const webSearchUsed = toolCallsExecuted.some((n) => n === 'web_search');

    // Only persist to chat_history when a sessionId was provided (the
    // standalone page sends one; the dashboard's inline tab does not).
    if (sessionId) {
      await supabase.from('founder_ai_chat_history').insert([
        { session_id: sessionId, role: 'user',      content: message,         created_at: new Date().toISOString() },
        { session_id: sessionId, role: 'assistant', content: assistantText,
          metadata: { web_search_used: webSearchUsed, tools_used: toolCallsExecuted },
          created_at: new Date().toISOString() },
      ]).then(() => undefined, (err) => console.error('chat_history insert failed:', err));
    }

    return NextResponse.json({
      // Both field names — `message` for the new client, `reply` for the
      // dashboard's existing inline tab that reads `data.reply`.
      message:       assistantText,
      reply:         assistantText,
      webSearchUsed,
      toolsUsed:     toolCallsExecuted,
      sessionId,
    });
  } catch (error) {
    // Surface the real cause so we can debug from the client without
    // having to chase Vercel function logs.
    const detail = error instanceof Error ? error.message : 'unknown';
    console.error('Founder AI route error:', error);
    return NextResponse.json({
      error: `Founder AI failed: ${detail}`,
      reply: `Sorry, I hit an error: ${detail}. Try again, or ask Dedrick to check the route logs.`,
    }, { status: 500 });
  }
}

export async function GET(req: NextRequest) {
  try {
    const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_KEY;
    if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !serviceKey) {
      return NextResponse.json({
        error: 'Supabase env not configured (need NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY)',
        reply: 'AI is not configured (missing Supabase server key). Please contact Dedrick.',
      }, { status: 500 });
    }
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL,
      serviceKey,
    );

    const { searchParams } = new URL(req.url);
    const sessionId = searchParams.get('sessionId');

    if (!sessionId) {
      return NextResponse.json({ error: 'sessionId required' }, { status: 400 });
    }

    const { data, error } = await supabase
      .from('founder_ai_chat_history')
      .select('role, content, metadata, created_at')
      .eq('session_id', sessionId)
      .order('created_at', { ascending: true });

    if (error) return NextResponse.json({ error: 'Failed to load history' }, { status: 500 });

    return NextResponse.json({ history: data });
  } catch (error) {
    console.error('History fetch error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
