'use client';

// app/founder/statements/page.tsx
//
// Founder approval queue for customer statements. Generated by the cron
// as 'pending'. Founder previews the PDF → Approve → Send (email /
// WhatsApp / print). NOTHING sends without an explicit approve + send.

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { createBrowserClient } from '@supabase/ssr';

export const dynamic = 'force-dynamic';

type Snap = { full_name?: string; phone?: string; email?: string } | null;
type Stmt = {
  id: string; customer_id: string; period_start: string | null; period_end: string;
  status: string; trigger_reason: string; total_invoiced: number | null; total_paid: number | null;
  total_outstanding: number | null; account_status: string | null; customer_snapshot: Snap;
  approved_at: string | null; sent_at: string | null; sent_channel: string | null; pdf_url: string | null;
};

let _sb: ReturnType<typeof createBrowserClient> | null = null;
function sb() { if (!_sb) _sb = createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!); return _sb; }
const INK = '#060d1f', GOLD = '#f5c518', BORDER = '#1e3a5f';
const TABS = ['pending', 'approved', 'sent', 'all'] as const;

async function api(path: string, init?: RequestInit) {
  const { data: { session } } = await sb().auth.getSession();
  const res = await fetch(path, { ...init, headers: { ...(init?.headers ?? {}), Authorization: `Bearer ${session?.access_token ?? ''}`, ...(init?.body ? { 'Content-Type': 'application/json' } : {}) }, cache: 'no-store' });
  return res.json().catch(() => ({ ok: false, error: `HTTP ${res.status}` }));
}

function statusColor(s: string | null) {
  if (s === 'OVERDUE') return '#f87171';
  if (s === 'DUE') return '#fbbf24';
  return '#4ade80';
}

export default function StatementsPage() {
  const [tab, setTab] = useState<typeof TABS[number]>('pending');
  const [rows, setRows] = useState<Stmt[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);

  const load = useCallback(async () => {
    setError(null);
    const j = await api(`/api/founder/statements?status=${tab}`);
    if (!j.ok) { setError(j.error || 'Founder only'); return; }
    setRows(j.statements as Stmt[]);
  }, [tab]);
  useEffect(() => { load(); }, [load]);

  async function act(id: string, action: string, channel?: string) {
    setBusy(`${id}:${action}:${channel ?? ''}`);
    const j = await api('/api/founder/statements', { method: 'POST', body: JSON.stringify({ action, id, channel }) });
    setBusy(null);
    if (!j.ok) { setError(j.error || 'Action failed'); return; }
    if (action === 'send' && channel === 'print' && j.print_url) window.open(j.print_url, '_blank');
    load();
  }

  return (
    <div style={{ minHeight: '100vh', background: INK, color: '#fff', fontFamily: 'system-ui, -apple-system, sans-serif', padding: 16, paddingBottom: 80 }}>
      <div style={{ maxWidth: 980, margin: '0 auto' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
          <div><div style={{ color: GOLD, fontWeight: 900, fontSize: 22 }}>🧾 Customer Statements</div>
            <div style={{ color: 'rgba(255,255,255,0.5)', fontSize: 12 }}>Approve, then send (email · WhatsApp · print). Nothing sends without your approval.</div></div>
          <Link href="/founder" style={pill}>← Founder</Link>
        </div>
        {error && <div style={{ color: '#f87171', fontSize: 13, marginBottom: 10 }}>⚠ {error}</div>}

        <div style={{ display: 'flex', gap: 6, marginBottom: 12 }}>
          {TABS.map((t) => (
            <button key={t} onClick={() => setTab(t)} style={{ ...pill, cursor: 'pointer', background: tab === t ? GOLD : 'transparent', color: tab === t ? INK : '#cbd5e1', fontWeight: tab === t ? 800 : 500, textTransform: 'capitalize' }}>{t}</button>
          ))}
        </div>

        {rows.length === 0 && <div style={{ color: '#64748b', fontSize: 14, padding: 20, textAlign: 'center' }}>No {tab} statements.</div>}

        {rows.map((s) => {
          const name = s.customer_snapshot?.full_name || 'Customer';
          return (
            <div key={s.id} style={card}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10, flexWrap: 'wrap' }}>
                <div>
                  <div style={{ fontWeight: 800, fontSize: 15 }}>{name}
                    <span style={{ marginLeft: 8, fontSize: 11, fontWeight: 800, color: statusColor(s.account_status) }}>{s.account_status}</span>
                    {s.trigger_reason === 'credit_breach' && <span style={{ marginLeft: 8, fontSize: 10, background: '#7f1d1d', color: '#fecaca', padding: '1px 6px', borderRadius: 4 }}>⚠ CREDIT BREACH</span>}
                  </div>
                  <div style={{ fontSize: 11, color: '#94a3b8', marginTop: 2 }}>
                    Period {s.period_start || '—'} → {s.period_end} · {s.customer_snapshot?.email || 'no email'} · {s.customer_snapshot?.phone || 'no phone'}
                  </div>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ fontSize: 18, fontWeight: 900, color: GOLD }}>${Number(s.total_outstanding ?? 0).toFixed(2)}</div>
                  <div style={{ fontSize: 10, color: '#94a3b8' }}>outstanding · inv ${Number(s.total_invoiced ?? 0).toFixed(2)} · paid ${Number(s.total_paid ?? 0).toFixed(2)}</div>
                </div>
              </div>

              <div style={{ display: 'flex', gap: 8, marginTop: 10, flexWrap: 'wrap', alignItems: 'center' }}>
                {s.pdf_url && <a href={s.pdf_url} target="_blank" rel="noreferrer" style={{ ...pill, color: '#93c5fd' }}>👁 Preview PDF</a>}
                <span style={{ fontSize: 11, color: '#64748b', textTransform: 'uppercase', letterSpacing: 1 }}>{s.status}{s.sent_channel ? ` · ${s.sent_channel}` : ''}</span>
                <div style={{ flex: 1 }} />
                {s.status === 'pending' && (
                  <button onClick={() => act(s.id, 'approve')} disabled={!!busy} style={{ ...btn, background: GOLD, color: INK }}>{busy === `${s.id}:approve:` ? '…' : '✓ Approve'}</button>
                )}
                {(s.status === 'approved' || s.status === 'sent') && (
                  <>
                    <button onClick={() => act(s.id, 'send', 'email')} disabled={!!busy} style={btn}>✉ Email</button>
                    <button onClick={() => act(s.id, 'send', 'whatsapp')} disabled={!!busy} style={btn}>💬 WhatsApp</button>
                    <button onClick={() => act(s.id, 'send', 'print')} disabled={!!busy} style={btn}>🖨 Print</button>
                  </>
                )}
                {s.status !== 'void' && s.status !== 'sent' && (
                  <button onClick={() => act(s.id, 'void')} disabled={!!busy} style={{ ...btn, color: '#f87171', borderColor: '#7f1d1d' }}>Void</button>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

const card: React.CSSProperties = { background: '#0a1628', border: `1px solid ${BORDER}`, borderRadius: 12, padding: 14, marginBottom: 10 };
const pill: React.CSSProperties = { color: '#cbd5e1', fontSize: 13, textDecoration: 'none', border: `1px solid ${BORDER}`, borderRadius: 8, padding: '7px 12px' };
const btn: React.CSSProperties = { fontSize: 12, fontWeight: 700, border: `1px solid ${BORDER}`, borderRadius: 8, padding: '7px 12px', background: 'transparent', color: '#cbd5e1', cursor: 'pointer' };
